Song.create(song_name: "Legend", album_name: "If You're Reading This It's Too Late", release_date: 2015, artist: "Drake", mood: "Hype Mode", on_itunes: true)
Song.create(song_name: "Energy", album_name: "If You're Reading This It's Too Late", release_date: 2015, artist: "Drake", mood: "Hype Mode", on_itunes: true)
Song.create(song_name: "10 Bands", album_name: "If You're Reading This It's Too Late", release_date: 2015, artist: "Drake", mood: "Hype Mode", on_itunes: true)
Song.create(song_name: "Know Yourself", album_name: "If You're Reading This It's Too Late", release_date: 2015, artist: "Drake", mood: "Hype Mode", on_itunes: true)
Song.create(song_name: "No Tellin", album_name: "If You're Reading This It's Too Late", release_date: 2015, artist: "Drake", mood: "Hype Mode", on_itunes: true)
Song.create(song_name: "Marvin's Room", album_name: "Take Care", release_date: 2011, artist: "Drake", mood: "Don't Drake and Drive", on_itunes: true)
Song.create(song_name: "Doing It Wrong", album_name: "Take Care", release_date: 2011, artist: "Drake", mood: "Don't Drake and Drive", on_itunes: true)
Song.create(song_name: "Practice", album_name: "Take Care", release_date: 2011, artist: "Drake", mood: "Don't Drake and Drive", on_itunes: true)
Song.create(song_name: "Connect", album_name: "Nothing Was The Same", release_date: 2013, artist: "Drake", mood: "Don't Drake and Drive", on_itunes: true)
Song.create(song_name: "Best I Ever Had", album_name: "So Far Gone", release_date: 2009, artist: "Drake", mood: "Don't Drake and Drive", on_itunes: true)
Song.create(song_name: "Successful", album_name: "So Far Gone", release_date: 2009, artist: "Drake", mood: "Money Monday", on_itunes: true)
Song.create(song_name: "Nice For What", album_name: "Scorpion", release_date: 2018, artist: "Drake", mood: "Money Monday", on_itunes: true)
Song.create(song_name: "Nonstop", album_name: "Scorpion", release_date: 2018, artist: "Drake", mood: "Money Monday", on_itunes: true)
Song.create(song_name: "The Motto", album_name: "Take Care", release_date: 2011, artist: "Drake", mood: "Money Monday", on_itunes: true)
Song.create(song_name: "Headlines", album_name: "Take Care", release_date: 2011, artist: "Drake", mood: "Money Monday", on_itunes: true)
Song.create(song_name: "Passionfruit", album_name: "More Life", release_date: 2017, artist: "Drake", mood: "Feel Good", on_itunes: true)
Song.create(song_name: "God's Plan", album_name: "Scorpion", release_date: 2018, artist: "Drake", mood: "Feel Good", on_itunes: true)
Song.create(song_name: "Hotline Bling", album_name: "Views", release_date: 2016, artist: "Drake", mood: "Feel Good", on_itunes: true)
Song.create(song_name: "Shut It Down", album_name: "Thank Me Later", release_date: 2010, artist: "Drake", mood: "Feel Good", on_itunes: true)
Song.create(song_name: "Up All Night", album_name: "Thank Me Later", release_date: 2010, artist: "Drake", mood: "Feel Good", on_itunes: true)
Song.create(song_name: "Controlla", album_name: "Views", release_date: 2016, artist: "Drake", mood: "Dance Party", on_itunes: true)
Song.create(song_name: "HYFR", album_name: "Take Care", release_date: 2011, artist: "Drake", mood: "Dance Party", on_itunes: true)
Song.create(song_name: "One Dance", album_name: "Views", release_date: 2016, artist: "Drake", mood: "Dance Party", on_itunes: true)
Song.create(song_name: "Too Good", album_name: "Views", release_date: 2016, artist: "Drake", mood: "Dance Party", on_itunes: true)
Song.create(song_name: "In My Feelings", album_name: "Scorpion", release_date: 2018, artist: "Drake", mood: "Dance Party", on_itunes: true)
